services:
  postgres:
    image: postgres:latest
    container_name: cronos-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: cronos_user
      POSTGRES_PASSWORD: cronos_pass
      POSTGRES_DB: cronos_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
