services:
  postgres:
    image: postgres:latest
    container_name: cronos-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: cronos_user
      POSTGRES_PASSWORD: cronos_pass
      POSTGRES_DB: cronos_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cronos_user -d cronos_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  postgres-test:
    image: postgres:latest
    container_name: cronos-test-db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: cronos_user
      POSTGRES_PASSWORD: cronos_pass
      POSTGRES_DB: cronos_test_db
    volumes:
      - pgdata-test:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cronos_user -d cronos_test_db"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  pgdata:
  pgdata-test: